name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  automated-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter
      - name: List JMeter Installation
        run: |
          echo "Listing JMeter Installation:"
          ls -la /usr/share/jmeter/bin/
      - name: List Files in Working Directory
        run: |
          echo "Listing files in the working directory:"
          ls -la
      - name: Run JMeter Tests
        run: |
          jmeter -n -t "script/HTTP.jmx" -l "test_results.jtl" 
      - name: Generate HTML Report
        run: |
          jmeter -g "test_results.jtl" -o "html-report"
      - name: Upload Test Results
        if: always()  # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-jtl-results
          path: test_results.jtl

      - name: Upload HTML Results
        if: always()  # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: html-report
