name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Apache JMeter
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      # Run JMeter Test (.jmx file)
      - name: Run JMeter test
        run: |
          jmeter -n -t script/HTTP.jmx -l results.jtl

      # Upload test results as artifacts (optional)
      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl
