name: JMeter Test CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Jobs define the tasks that are run
jobs:
  jmeter-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install JMeter on Windows
        run: |
          choco install jmeter -y

      - name: Verify Test Files
        run: |
          if (Test-Path ".\github\workflows\HTTP_Request-000226.jmx") { 
            Write-Host "Test plan found."
          } else {
            Write-Host "Error: Test plan not found!"
            exit 1
          }
          if (Test-Path ".\github\workflows\EdwiseCsv.csv") { 
            Write-Host "CSV file found."
          } else {
            Write-Host "Error: CSV file not found!"
            exit 1
          }

      - name: Run JMeter Test
        run: |
          jmeter -n -t ".\github\workflows\HTTP_Request-000226.jmx" \
                 -l ".\github\workflows\results.jtl" \
                 -Jcsv_file=".\\github\\workflows\\EdwiseCsv.csv" \
                 -Jjmeter.save.saveservice.output_format=xml \
                 -j ".\github\workflows\jmeter.log"

      - name: Show JMeter Logs
        run: |
          type ".\github\workflows\jmeter.log"

      - name: Generate JMeter HTML Report from the results
        run: |
          jmeter -g ".\github\workflows\results.jtl" `
                 -o ".\github\workflows\report"

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-report
          path: .\github\workflows\report
